### ISSUE TITLE
Coś pięknego

### ISSUE THREAD

**Issue by JulianLejk** [TomaszBar/ProjektZespolowy#1]
Niech każdy sprawdzi i doda coś od siebie. Na razie wrzuciłem tutaj żeby było widać postępy, czy coś. Jak będzie ostateczna wersja to lece z Gantt'em
24.02   Założenie grupy projektowej, wybór tematu. Ustalenie i podział zadań. Projektowanie   dokumentacji wstępnej(protokół założycielski, lista funkcjonalności, harmonogram)
2.03    Stworzenie architektury dla aplikacji(diagramy)
9.03    Implementacja głównych klas 
16.03   Implementacja GUI
23.03   Testy 
30.03   Utworzenie specyfikacji wymagań
6.04    Implementacja podstawowych funkcjonalności
13.04   Implementacja mechanizmów walidacji
20.04   Stworzenie działającej wersji Beta
27.04   Testy 
11.05   Upgrade dokumentacji
18.05   Implementacja funkcjonalności
25.05   Implementacja funkcjonalnośći
1.06            Testy ostateczne aplikacji
8.06    Kompletna dokumentacja

**Comment by DianaDzik** [comment]
jest ok :)

**Comment by MichalBenedysiuk** [comment]
da radę :)

**Comment by MichalBenedysiuk** [comment]
zmień daty na od -do (np. 2.03 - 9.03 - Stworzenie architektury dla aplikacji(diagramy))

**Comment by MichalBenedysiuk** [comment]
rozbudować harmonogram (podzielić zadania na podzadania, dokładniejsze opisy. Napisanie co kto robi.
