### ISSUE TITLE
Harmonogram

### ISSUE THREAD

**Issue by JulianLejk** [TomaszBar/ProjektZespolowy#3]
Niech każdy przeczyta i może coś jeszcze zasugeruje.

**Comment by JulianLejk** [comment]
już jest końcowy harmonogram, sprawdźcie czy wszystko gra.

**Comment by DianaDzik** [comment]
Proponuje zrobić folder na harmonogram jeśli chcesz trzymać wszystkie wersje. Poproszę o wersje w pdf :) harmonogram mało przejrzysty, co do treści ja nie mam zastrzeżeń, potrzebna opinia koderów :)
