### ISSUE TITLE
Diagram klas

### ISSUE THREAD

**Issue by patrycjaj** [TomaszBar/ProjektZespolowy#4]
zrobiłam diagram, jak sami widzicie jest koło 2, więc może nie byc idealnie. starałam się ;) dajcie znac jak cos jest nie tak

**Comment by patrycjaj** [comment]
wrzucilam poprawiony diagram klas do dokumentacji, ograniczone do 3 klas tak, aby to jak najbardziej uproscić

**Comment by GrzegorzWolos7** [comment]
Logowanie oraz algorytm logowania

**Comment by GrzegorzWolos7** [comment]
[src.zip](https://github.com/TomaszBar/ProjektZespolowy/files/185671/src.zip)
